sudo: required
language: generic
services:
  - docker


before_install: 
  - docker build -t michaelfama/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true michaelfama/docker-react npm run test